#!/usr/bin/env php
<?php

$_ENV['VAGRANT_DOTFILE_PATH'] = '~/.entropy/.vagrant';

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
	require __DIR__.'/vendor/autoload.php';
}
else
{
	require __DIR__.'/../../autoload.php';
}

function entropy_path()
{
	if (isset($_SERVER['HOME']))
	{
		return $_SERVER['HOME'].'/.entropy';
	}
	else
	{
		return $_SERVER['HOMEDRIVE'].$_SERVER['HOMEPATH'].DIRECTORY_SEPARATOR.'.entropy';
	}
}

$app = new Symfony\Component\Console\Application('Entropy', '2.1.0');

$app->add(new Ammonkc\Entropy\DestroyCommand);
$app->add(new Ammonkc\Entropy\EditCommand);
$app->add(new Ammonkc\Entropy\HaltCommand);
$app->add(new Ammonkc\Entropy\InitCommand);
$app->add(new Ammonkc\Entropy\ResumeCommand);
$app->add(new Ammonkc\Entropy\RunCommand);
$app->add(new Ammonkc\Entropy\UpCommand);
$app->add(new Ammonkc\Entropy\UpdateCommand);
$app->add(new Ammonkc\Entropy\SshCommand);
$app->add(new Ammonkc\Entropy\StatusCommand);
$app->add(new Ammonkc\Entropy\SuspendCommand);

$app->run();
